version: '3.8'

services:
  dev:
    container_name: craftnote-robot
    restart: always
    build: 
      context: .
      target: prod
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app